.TH HARP 1 "September 2014" "HARP 0.6.0" "User Commands"
.SH NAME
harp \- play and manage music
.SH SYNOPSIS
\fBharp\fP [\fBoptions\fP]
.SH OPTIONS
.TP
\fB\-t\fP,\fB --type=\fP[type]
Specify the type of object to perform an action on. Required for insert, list, or play. Valid types are: [s]ong, [p]laylist, a[r]tist, [a]lbum, [g]enre, [t]ag.
.TP
\fB\-i\fP,\fB --insert=\fP{song path | directory}
Insert song(s) into the database. By passing a directory as an argument, HARP will recursively scan the directory and insert all valid files. Use with no argument to enter information at a prompt.
.TP
\fB\-E\fP,\fB --edit=\fP{edit commands}
Edit information stored in the database.
.TP
\fB\-e\fP,\fB --edit-stdin\fP
Edit information stored in the database. Commands will be accepted over stdin.
.TP
\fB\-E\fP,\fB --old-edit\fP
Edit information stored in the database using the deprecated portal interface.
.TP
\fB\-l\fP,\fB --list=\fP[unique name | id]
List information from the database. Use with no argument to display all entries.
.TP
\fB\-s\fP,\fB --shuffle\fP[s | a | r]
When combined with the play option, shuffle the selected songs. The given argument will determine whether songs, albums, or artists are shuffled.
.TP
\fB\-z\fP,\fB --zshuffle\fP
When combined with the play option, shuffle the selected songs with statistical modifiers.
.TP
\fB\-r\fP,\fB --repeat\fP[number of repeats]
When combined with the play option, repeat the generated playlist indefinitely or the specified number of times.
.TP
\fB\-D\fP,\fB --device=\fP{device name}
When combined with the play option, output audio to the specified device.
.TP
\fB\-p\fP,\fB --play=\fP[unique name | id]
Play the songs listed under the name or id in the specified type.
.TP
\fB\-a\fP,\fB --admin\fP
Enter the admin utility to manage plugins and song statistics.
.TP
\fB\-v\fP,\fB --verbose\fP
Print debug messages. Call more than once for more messages.
.TP
\fB --version\fP
Print version information.
.SH PLAYER CONTROLS
.TP
.B q
Quit
.TP
.B n
Next
.TP
.B N
Next without updating play statistics
.TP
.B p
Restart song
.TP
.B 9
Volume down
.TP
.B 0
Volume up
.TP
.B m
Mute
.TP
.B ,
Seek backward
.TP 
.B .
Seek forward
.TP
.B [space]
Pause
.TP
.B r
Decrease rating
.TP
.B R
Increase rating
.TP
.B :
Enter advanced player command prompt.
.SH ADVANCED PLAYER COMMANDS
.TP
.B l
List the contents of the current playlist. Provide a numerical argument (e.g., :l25) to specify the maximum number of songs printed. The default value is 30.
.RS
.TP
.B lh
List from the head of the playlist.
.TP
.B lt
List from the tail of the playlist.
.TP
.B lr
List from the current position the playlist. (default)
.RE
.TP
.B j
Jump to a new position in the playlist. Provide a numerical argument (e.g., :j34) to specify the location. The jump has an effect similar to next (i.e., increased skip count). To jump without updating the play statistics for the skipped song, substitute 'j' with 'J'.
.RS
.TP
.B js
Jump to a location based on SongID.
.TP
.B jo
Jump to a location based on Order. (default)
.RE
.TP
.B ,
Seek backward a specified number of seconds. (e.g., :,50)
.TP
.B .
Seek forward a specified number of seconds. (e.g., :.50)
.TP
.B a
Add song(s) to the temporary playlist currently playing. By default, the songs will be added to the location directly following the current song. Songs can be specified by name, ID, or all songs by particular artists, albums, or genres may be added using a similar syntax to the edit menu. :a [s | a | r | g] [unique name | id]. (e.g., :a r special_artist)
.RS
.TP
.B ao
Specify the destination of the added songs. (e.g. To add special_song at order 12, :ao 12 s special_song)
.RE
.TP
.B r
Remove song(s) from the temporary playlist currently playing. Syntax is the same as the add command.
.RS
.TP
.B ro
Remove a single song at the specified order.
.RE
.TP
.B w
Save the current playlist. This command will overwrite any playlist previously saved with this command.
.SH FILES
.TP
~/.harp/defaults.conf
HARP user configuration file
.TP
/usr/local/share/harp/defaults.conf
Default HARP configuration file
.SH EXAMPLES
.B harp -ts -s -p1,43,SongName,2
.br
.RS
Plays the four selected songs in shuffled order.
.RE
.br
.B harp -v -i ~/music/
.br
.RS
Inserts the songs located under the ~/music/ directory with verbose output.
.RE
